### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by LucasGorgal** [kovleventer/WenkuBaiduDL#2]
```
http://ai.wenku.baidu.com/play/063028fba26925c52dc5bf13?pn=1&rn=5
Unknown option: -r
Traceback (most recent call last):
  File "wenku_baidu_dl.py", line 119, in <module>
    download_pdf(args.url, args.output, args.resolution, args.pages_per_query)
  File "wenku_baidu_dl.py", line 93, in download_pdf
    fromPage, end = download_one_block(doc_id, fromPage, resolution, pages_per_query)
  File "wenku_baidu_dl.py", line 72, in download_one_block
    convert_to_rgb(png_filename)
  File "wenku_baidu_dl.py", line 15, in convert_to_rgb
    image = Image.open(path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/0001.png'
```

**Comment by kovleventer** [comment]
Which version of swrender do you use? (you can check that by calling `swfrender --version`) Older versions do not support the -r flag, which my program uses, in that case I recommend updating that.
