### ISSUE TITLE
No JPEG library compiled

### ISSUE THREAD

**Issue by AnhDQHE181109** [kovleventer/WenkuBaiduDL#3]
When I was trying to download a document on that site, I encountered this error:
`http://ai.wenku.baidu.com/play/422c3c0516fc700abb68fc1b?pn=1&rn=5
rfxswf: Error: No JPEG library compiled inKilled
Traceback (most recent call last):
  File "wenku_baidu_dl.py", line 119, in <module>
    download_pdf(args.url, args.output, args.resolution, args.pages_per_query)
  File "wenku_baidu_dl.py", line 93, in download_pdf
    fromPage, end = download_one_block(doc_id, fromPage, resolution, pages_per_query)
  File "wenku_baidu_dl.py", line 72, in download_one_block
    convert_to_rgb(png_filename)
  File "wenku_baidu_dl.py", line 15, in convert_to_rgb
    image = Image.open(path)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/0001.png'
`
From what it said, I guess it's missing the JPEG library. But how do I properly install it?
Any help would be appreciated :)

**Comment by kovleventer** [comment]
Hi and thank you for the feedback!

It would be helpful if you provided info about the exact command you used and your platform (operating system, python version).

**Comment by AnhDQHE181109** [comment]
I'm currently using an Orange Pi Zero with Armbian Buster 5.20
With the Python version being 3
And here's the command that I attempted:
`python3 wenku_baidu_dl.py https://wenku.baidu.com/view/422c3c0516fc700abb68fc1b.html`

Edit: the OPi Zero also uses an ARM processor ;)

**Comment by kovleventer** [comment]
https://pillow.readthedocs.io/en/stable/installation.html#external-libraries

It seems pillow has a few dependencies and even though JPEG is not used (only PNG conversion occurs), you might still need to install libjpeg (probably as simple as issuing `apt-get install libjpeg`)

BUT this whole PIL package is only used to remove the occasional transparency channel from the images (it would cause an error if kept), so you might be able to get away with simply commenting out line 72 `convert_to_rgb(png_filename)`. It won't work every time this way, but as I saw, it did the job for the file you linked.

**Comment by AnhDQHE181109** [comment]
Alright, thank you for your suggestions :)

It seems that even after I install the `libjpeg-dev` package, it still throws that error.
And after I attempted downloading that file again (with the 72nd line commented out), it threw me this error:
`Error: No JPEG library compiled inSegmentation fault
rfxswf: Error: No JPEG library compiled inSegmentation fault
rfxswf: Error: No JPEG library compiled inSegmentation fault
rfxswf: Error: No JPEG library compiled inSegmentation fault
Traceback (most recent call last):
  File "wenku_baidu_dl.py", line 119, in <module>
    download_pdf(args.url, args.output, args.resolution, args.pages_per_query)
  File "wenku_baidu_dl.py", line 107, in download_pdf
    f.write(img2pdf.convert(filenames))
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1829, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1161, in read_images
    im = BytesIO(rawdata)
TypeError: a bytes-like object is required, not 'str'`

Followed by a bunch of 'No JPEG library compiled in'

And this is the last page request before everything breaks down:
`http://ai.wenku.baidu.com/play/422c3c0516fc700abb68fc1b?pn=41&rn=5`

I don't know why it said it couldn't find the JPEG library even though it's installed
Perhaps I need some more configurations?

**Comment by kovleventer** [comment]
Yeah, I should have known, even with commenting that line out, it will still use PIL indirectly from img2pdf.

I don't really have any other ideas, but it seems others had this problem as well on similar arm platforms, so this (https://raspberrypi.stackexchange.com/questions/9361/how-do-i-enable-jpeg-support-with-pil) might be useful (find the shared library, link it to /usr/lib if necessary, the reinstall PIL).

**Comment by AnhDQHE181109** [comment]
Oh well...

This might sound frustrating, but, the results are the same

I did what it said on that link
Uninstall Pillow (a fork of PIL), install libjpeg-dev and link the library where necessary, then reinstall Pillow
